
VERSION=$(shell cat version)

ifndef ($(PREFIX))
	PREFIX=/usr/local
endif

ifndef ($(INCLUDE_PATH))
	INCLUDE_PATH=$(PREFIX)/include/apq
endif

ifndef ($(LIB_PATH))
	LIB_PATH=$(PREFIX)/lib
endif

ifndef ($(GPR_PATH))
	GPR_PATH=$(LIB_PATH)/gnat 
endif



