# Makefile for the APQ
#
# @author Marcelo Coraça de Freitas <marcelo@kow.com.br> 

VERSION=3.0

ifndef ($(PREFIX))
	PREFIX=/usr/local
endif
INCLUDE_PREFIX=$(PREFIX)/include
LIB_PREFIX=$(PREFIX)/lib
GPR_PREFIX=$(LIB_PREFIX)/gnat



projectFile="apq.gpr"


all: libs gprfile

libs:
	gnatmake -P ${projectFile}

gprfile:
	@echo "Preparing GPR file.."
	@echo version:=\"$(VERSION)\" > gpr/apq.def
	@echo prefix:=\"$(PREFIX)\" >> gpr/apq.def
	@gnatprep gpr/apq.gpr.in gpr/apq.gpr gpr/apq.def




clean:
	@gnatclean -P ${projectFile}
	@rm -f gpr/apq.def gpr/apq.gpr
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"

install:
	@echo "Installing files"
	install -d $(INCLUDE_PREFIX)
	install -d $(LIB_PREFIX)
	install -d $(GPR_PREFIX)
	install src*/* -t $(INCLUDE_PREFIX)
	install lib/* -t $(LIB_PREFIX)
	install gpr/*.gpr -t $(GPR_PREFIX)
